try {
    console.log(x);
}
catch(error) {
    console.log("Error Name: ", error.name);
    console.log("Error Message: ", error.message);
}